### ISSUE TITLE
Comparison with Scrivener

### ISSUE THREAD

**Issue by mjsisley** [elixirdrops/kerosene#13]
Thanks for open sourcing this package!

Do you have a quick overview of the tradeoffs with [scrivener](https://github.com/drewolson/scrivener)?

**Comment by allyraza** [comment]
Hi,

Thank you for stopping by and checking it out, TBH kerosene was part of a project I worked on and it was based on early work by scrivener's author, he wrote a blog post regarding pagination with elixir and ecto, I extended that and used it later added more features and open sourced it, it is different in many ways kerosene has html helpers as well as a json support if you are building spa or apis, plus kerosene supports certain other features like params are converted to maps instead of keyword lists which are better for performance if you are sending lot of data through query params. you don't need additional queries you can just pass in schema structs and it will just work.

**Comment by mjsisley** [comment]
Thanks for the breakdown! 

I'm looking to do pagination over Phoenix Channels. It's a bit down the roadmap, but I'll send a PR if I end up using Kerosene as a starting point for this!

**Comment by allyraza** [comment]
let me know if you need some insight I can definitely help
