### ISSUE TITLE
Pagination not working properly with 0.8.0

### ISSUE THREAD

**Issue by supernova32** [elixirdrops/kerosene#41]
For some reason after the upgrade from 0.7.0 to 0.8.0, pagination stopped working properly. There are no errors on any of the logs, but the collection being returned per page is not correct.

It seems to me that the offset is not being correctly applied. I have a `per_page` of 10. On 0.7.0, page 2 correctly starts from the 11th item on my collection, but with 0.8.0, it seems to start on the 3rd or 4th, so it starts with items that were already shown on page 1.

And the last page does not have the last element of the collection. I don't think the problem lies in my configuration, given that everything worked fine on 0.7.0.

Thanks!

**Comment by rudigiesler** [comment]
The issue here resides in https://github.com/elixirdrops/kerosene/blob/master/lib/kerosene.ex#L54-L64 . That function is returning what page should be returned, not the offset (which is `page * per_page`)

That logic should probably move to `get_page`, and `get_offset` should be be `page * per_page`

**Comment by danturn** [comment]
Hi
I raised a PR for paginating non schema based queries that includes this fix:

https://github.com/elixirdrops/kerosene/pull/42

**Comment by allyraza** [comment]
sorry for the late reply folks, should be fixed thanks to @danturn PR has been merged. please upgrade your mix file to 0.8.1
